# Generated by Django 4.2.4 on 2023-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='booked_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
